version: '3.4'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./mysqlscript:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: STT
      MYSQL_USER: MySqlUSR
      MYSQL_PASSWORD: Password65!!
    
    ports:
      - "3300:3306"
  sst.webapi.api:
    depends_on:
      - "database"
    image: ${DOCKER_REGISTRY-}sstwebapiapi
    build:
      context: .
      dockerfile: ./SST.WebApi.API/Dockerfile
    ports:
      - "5800:443"
volumes:
  dbdata:

